name: Building Package using Conda

on:
  workflow_call:
    inputs:
      python-minor-versions: 
        description: 'Python minor versions to consider'
        required: false
        default: [7, 8, 9, 10, 11]
    secrets:
      token:
        description: 'Anaconda access Token (required)'
        required: true      

jobs:
  build-and-publish:
    name: ${{ matrix.os }}, Python 3.${{ matrix.python-minor-version }} for conda deployment
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , macos-latest , windows-latest]
        python-minor-version: ${{ inputs.python-minor-versions }}
        isMaster:
          - ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dev') }}
        exclude:
          - isMaster: false
            python-minor-version: 7
          - isMaster: false
            python-minor-version: 8
          - isMaster: false
            python-minor-version: 9
          - isMaster: false
            python-minor-version: 11
          - isMaster: false
            os: macos-latest
            python-minor-version: 10
          - isMaster: false
            os: windows-latest
            python-minor-version: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Determine publication
      uses: haya14busa/action-cond@v1
      id: publish
      with:
        cond: ${{ contains(github.ref, 'stable') || startsWith(github.ref, 'refs/heads/v') }}
        if_true: 'true'
        if_false: 'false'
    - name: Build and Publish
      uses: fredboudon/action-build-publish-anaconda@main
      with:
        conda: conda
        mamba: true
        python: ${{ matrix.python-minor-version }}
        numpy: '24'
        channels: fredboudon, conda-forge
        token: ${{ secrets.ANACONDA_TOKEN }}
        publish: ${{ steps.publish.outputs.value }}
        label: main
        buildoptions: '--no-test'
