name: Building Package using Conda

on:
  workflow_call:
    secrets:
      token:
        description: 'Anaconda access Token (required)'
        required: true      

jobs:
  build-and-publish:
    name: ${{ matrix.os }}, Python 3.${{ matrix.python-minor-version }} for conda deployment
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , macos-latest , windows-latest]
        python-minor-version: [8, 9, 10]
        isMaster:
          - ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
        exclude:
          - isMaster: false
            python-minor-version: 7
          - isMaster: false
            python-minor-version: 8
          - isMaster: false
            python-minor-version: 9
          - isMaster: false
            python-minor-version: 11
          - isMaster: false
            os: macos-latest
            python-minor-version: 10
          - isMaster: false
            os: windows-latest
            python-minor-version: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Determine publication
      uses: haya14busa/action-cond@v1
      id: publish
      with:
        cond: ${{ startsWith(github.ref, 'refs/tags/v') }}
        if_true: 'true'
        if_false: 'false'
    - name: Build and Publish
      uses: fredboudon/action-build-publish-anaconda@main
      with:
        conda: conda
        mamba: true
        python: ${{ matrix.python-minor-version }}
        numpy: '22'
        channels: fredboudon, conda-forge
        token: ${{ secrets.token }}
        publish: ${{ steps.publish.outputs.value }}
        label: main
        buildoptions: '--no-test'
